//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ResManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ResManager), typeof(Singleton<ResManager>));
		L.RegFunction("LoadAB", LoadAB);
		L.RegFunction("LoadGameObject", LoadGameObject);
		L.RegFunction("Unload", Unload);
		L.RegFunction("ClearAB", ClearAB);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadAB(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ResManager obj = (ResManager)ToLua.CheckObject<ResManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.LoadAB(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadGameObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			ResManager obj = (ResManager)ToLua.CheckObject<ResManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			UnityEngine.GameObject o = obj.LoadGameObject(arg0, arg1);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Unload(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ResManager obj = (ResManager)ToLua.CheckObject<ResManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.Unload(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearAB(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ResManager obj = (ResManager)ToLua.CheckObject<ResManager>(L, 1);
			obj.ClearAB();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

